baseurl: "https://hugo1.abyss.codes"
title: "Hugo 1"

author:
  name: "Abyss"

params:
  # Subtitle for home
  homeSubtitle: "Home Subtitle 1"

  # Default theme "light" or "dark"
  defaultTheme: "dark"

languages:
  en:
    title: "Hugo Demo 1"
