baseurl: "https://hugo2.abyss.codes"
title: "Hugo 2"

author:
  name: "Craig"

params:
  # Subtitle for home
  homeSubtitle: "Home Subtitle 2"

  # Default theme "light" or "dark"
  defaultTheme: "light"

  social:
    extra:
      - name: linkedin
        url: https://www.linkedin.com/in/craig-reeder/

languages:
  en:
    title: "Hugo Demo 2"

menu:
  extra:
    - name: "Resume"
      identifier: "resume"
      url: ""
