baseurl: "https://hugo2.abyss.codes"
title: "Hugo 2"

author:
  name: "Craig"

params:
  # Default theme "light" or "dark"
  defaultTheme: "light"

  social:
    extra:
      - name: linkedin
        url: https://www.linkedin.com/

menu:
  extra:
    - name: "Resume"
      identifier: "resume"
      url: ""
