name: hugo2-deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.1"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify --environment hugo2

      - name: Deploy site 2
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          external_repository: abyss/hugo-proof-of-concept-d2
          publish_dir: ./public
          # keep_files: true
          user_name: abyss
          user_email: abyss@users.noreply.github.com
          publish_branch: master
          cname: hugo2.abyss.codes
